---

# Example sandbox configuration
# for single server community
# installs

- name: Configure UPEx databases
  hosts: localhost
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - edxlocal
    - mongo
    - { role: 'rabbitmq', rabbitmq_ip: '10.0.3.200' }
    - oraclejdk
    - elasticsearch
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
